on: push

jobs:
  npm-build:
    name: npm-buildå·¥ä½œ
    runs-on: ubuntu-latest

    steps:
    - name: è¯»å–ä»“åº“å†…å®¹ğŸ¤”
      uses: actions/checkout@v4

    - name: å®‰è£…ä¾èµ–ğŸš€å’Œé¡¹ç›®æ‰“åŒ…ğŸ“¦
      run: 
        npm install
        npm run build

    - name : éƒ¨ç½²åˆ°GitHub PagesğŸŒ
      uses: JamesIves/github-pages-deploy-action@v4
      with :
        branch: gh-pages
        folder: build
    