name: æ„å»ºå¹¶æ¨é€Dockeré•œåƒ
on: push

jobs:
  npm-build:
    name: npm-buildå·¥ä½œ
    runs-on: ubuntu-latest

    steps:
    - name: è¯»å–ä»“åº“å†…å®¹ğŸ¤”
      uses: actions/checkout@v4

    - name: ç™»å½•DockerHubğŸ”
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: æ„å»ºå¹¶æ¨é€åˆ°Docker HubğŸ³
      uses: docker/build-push-action@v5
      with :
        push: true
        tags: zwawa/react-app-study:latest
